package com.chawuzhi.novel.domain;

public class HistoryStoreKey extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_store.table_name
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_store.pk_date_dest
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    private String pkDateDest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_store.table_name
     *
     * @return the value of history_store.table_name
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_store.table_name
     *
     * @param tableName the value for history_store.table_name
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_store.pk_date_dest
     *
     * @return the value of history_store.pk_date_dest
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public String getPkDateDest() {
        return pkDateDest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_store.pk_date_dest
     *
     * @param pkDateDest the value for history_store.pk_date_dest
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public void setPkDateDest(String pkDateDest) {
        this.pkDateDest = pkDateDest == null ? null : pkDateDest.trim();
    }
}