package com.chawuzhi.novel.domain;

import java.util.Date;

public class TBook extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.id
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_name
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.pinyin_headchar
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String pinyinHeadchar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.book_author
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String bookAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.category
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.intro
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.keyword
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.address
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.chapters
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private Integer chapters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.last_chapter_no
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private Integer lastChapterNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.last_chapter
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String lastChapter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.creater_no
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String createrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.create_time
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.modifier_no
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String modifierNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.modifiy_time
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private Date modifiyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.use_customize_info_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private Byte useCustomizeInfoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.info_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String infoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.info_keywords
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String infoKeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.info_description
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String infoDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.use_customize_list_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private Byte useCustomizeListTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.list_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String listTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.list_keywords
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String listKeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.list_description
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String listDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_book.pinyin
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.id
     *
     * @return the value of t_book.id
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.id
     *
     * @param id the value for t_book.id
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_name
     *
     * @return the value of t_book.book_name
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_name
     *
     * @param bookName the value for t_book.book_name
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.pinyin_headchar
     *
     * @return the value of t_book.pinyin_headchar
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getPinyinHeadchar() {
        return pinyinHeadchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.pinyin_headchar
     *
     * @param pinyinHeadchar the value for t_book.pinyin_headchar
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setPinyinHeadchar(String pinyinHeadchar) {
        this.pinyinHeadchar = pinyinHeadchar == null ? null : pinyinHeadchar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.book_author
     *
     * @return the value of t_book.book_author
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.book_author
     *
     * @param bookAuthor the value for t_book.book_author
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.category
     *
     * @return the value of t_book.category
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.category
     *
     * @param category the value for t_book.category
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.intro
     *
     * @return the value of t_book.intro
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.intro
     *
     * @param intro the value for t_book.intro
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.keyword
     *
     * @return the value of t_book.keyword
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.keyword
     *
     * @param keyword the value for t_book.keyword
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.address
     *
     * @return the value of t_book.address
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.address
     *
     * @param address the value for t_book.address
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.chapters
     *
     * @return the value of t_book.chapters
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public Integer getChapters() {
        return chapters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.chapters
     *
     * @param chapters the value for t_book.chapters
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setChapters(Integer chapters) {
        this.chapters = chapters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.last_chapter_no
     *
     * @return the value of t_book.last_chapter_no
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public Integer getLastChapterNo() {
        return lastChapterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.last_chapter_no
     *
     * @param lastChapterNo the value for t_book.last_chapter_no
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setLastChapterNo(Integer lastChapterNo) {
        this.lastChapterNo = lastChapterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.last_chapter
     *
     * @return the value of t_book.last_chapter
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getLastChapter() {
        return lastChapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.last_chapter
     *
     * @param lastChapter the value for t_book.last_chapter
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setLastChapter(String lastChapter) {
        this.lastChapter = lastChapter == null ? null : lastChapter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.creater_no
     *
     * @return the value of t_book.creater_no
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getCreaterNo() {
        return createrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.creater_no
     *
     * @param createrNo the value for t_book.creater_no
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setCreaterNo(String createrNo) {
        this.createrNo = createrNo == null ? null : createrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.create_time
     *
     * @return the value of t_book.create_time
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.create_time
     *
     * @param createTime the value for t_book.create_time
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.modifier_no
     *
     * @return the value of t_book.modifier_no
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getModifierNo() {
        return modifierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.modifier_no
     *
     * @param modifierNo the value for t_book.modifier_no
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setModifierNo(String modifierNo) {
        this.modifierNo = modifierNo == null ? null : modifierNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.modifiy_time
     *
     * @return the value of t_book.modifiy_time
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public Date getModifiyTime() {
        return modifiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.modifiy_time
     *
     * @param modifiyTime the value for t_book.modifiy_time
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setModifiyTime(Date modifiyTime) {
        this.modifiyTime = modifiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.use_customize_info_title
     *
     * @return the value of t_book.use_customize_info_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public Byte getUseCustomizeInfoTitle() {
        return useCustomizeInfoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.use_customize_info_title
     *
     * @param useCustomizeInfoTitle the value for t_book.use_customize_info_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setUseCustomizeInfoTitle(Byte useCustomizeInfoTitle) {
        this.useCustomizeInfoTitle = useCustomizeInfoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.info_title
     *
     * @return the value of t_book.info_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getInfoTitle() {
        return infoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.info_title
     *
     * @param infoTitle the value for t_book.info_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setInfoTitle(String infoTitle) {
        this.infoTitle = infoTitle == null ? null : infoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.info_keywords
     *
     * @return the value of t_book.info_keywords
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getInfoKeywords() {
        return infoKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.info_keywords
     *
     * @param infoKeywords the value for t_book.info_keywords
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setInfoKeywords(String infoKeywords) {
        this.infoKeywords = infoKeywords == null ? null : infoKeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.info_description
     *
     * @return the value of t_book.info_description
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getInfoDescription() {
        return infoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.info_description
     *
     * @param infoDescription the value for t_book.info_description
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setInfoDescription(String infoDescription) {
        this.infoDescription = infoDescription == null ? null : infoDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.use_customize_list_title
     *
     * @return the value of t_book.use_customize_list_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public Byte getUseCustomizeListTitle() {
        return useCustomizeListTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.use_customize_list_title
     *
     * @param useCustomizeListTitle the value for t_book.use_customize_list_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setUseCustomizeListTitle(Byte useCustomizeListTitle) {
        this.useCustomizeListTitle = useCustomizeListTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.list_title
     *
     * @return the value of t_book.list_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getListTitle() {
        return listTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.list_title
     *
     * @param listTitle the value for t_book.list_title
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setListTitle(String listTitle) {
        this.listTitle = listTitle == null ? null : listTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.list_keywords
     *
     * @return the value of t_book.list_keywords
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getListKeywords() {
        return listKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.list_keywords
     *
     * @param listKeywords the value for t_book.list_keywords
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setListKeywords(String listKeywords) {
        this.listKeywords = listKeywords == null ? null : listKeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.list_description
     *
     * @return the value of t_book.list_description
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getListDescription() {
        return listDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.list_description
     *
     * @param listDescription the value for t_book.list_description
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setListDescription(String listDescription) {
        this.listDescription = listDescription == null ? null : listDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_book.pinyin
     *
     * @return the value of t_book.pinyin
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_book.pinyin
     *
     * @param pinyin the value for t_book.pinyin
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
}