package com.chawuzhi.novel.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TBookcaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public TBookcaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBookcasenoIsNull() {
            addCriterion("bookcaseno is null");
            return (Criteria) this;
        }

        public Criteria andBookcasenoIsNotNull() {
            addCriterion("bookcaseno is not null");
            return (Criteria) this;
        }

        public Criteria andBookcasenoEqualTo(Integer value) {
            addCriterion("bookcaseno =", value, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andBookcasenoNotEqualTo(Integer value) {
            addCriterion("bookcaseno <>", value, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andBookcasenoGreaterThan(Integer value) {
            addCriterion("bookcaseno >", value, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andBookcasenoGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookcaseno >=", value, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andBookcasenoLessThan(Integer value) {
            addCriterion("bookcaseno <", value, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andBookcasenoLessThanOrEqualTo(Integer value) {
            addCriterion("bookcaseno <=", value, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andBookcasenoIn(List<Integer> values) {
            addCriterion("bookcaseno in", values, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andBookcasenoNotIn(List<Integer> values) {
            addCriterion("bookcaseno not in", values, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andBookcasenoBetween(Integer value1, Integer value2) {
            addCriterion("bookcaseno between", value1, value2, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andBookcasenoNotBetween(Integer value1, Integer value2) {
            addCriterion("bookcaseno not between", value1, value2, "bookcaseno");
            return (Criteria) this;
        }

        public Criteria andArticlenoIsNull() {
            addCriterion("articleno is null");
            return (Criteria) this;
        }

        public Criteria andArticlenoIsNotNull() {
            addCriterion("articleno is not null");
            return (Criteria) this;
        }

        public Criteria andArticlenoEqualTo(Integer value) {
            addCriterion("articleno =", value, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenoNotEqualTo(Integer value) {
            addCriterion("articleno <>", value, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenoGreaterThan(Integer value) {
            addCriterion("articleno >", value, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenoGreaterThanOrEqualTo(Integer value) {
            addCriterion("articleno >=", value, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenoLessThan(Integer value) {
            addCriterion("articleno <", value, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenoLessThanOrEqualTo(Integer value) {
            addCriterion("articleno <=", value, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenoIn(List<Integer> values) {
            addCriterion("articleno in", values, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenoNotIn(List<Integer> values) {
            addCriterion("articleno not in", values, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenoBetween(Integer value1, Integer value2) {
            addCriterion("articleno between", value1, value2, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenoNotBetween(Integer value1, Integer value2) {
            addCriterion("articleno not between", value1, value2, "articleno");
            return (Criteria) this;
        }

        public Criteria andArticlenameIsNull() {
            addCriterion("articlename is null");
            return (Criteria) this;
        }

        public Criteria andArticlenameIsNotNull() {
            addCriterion("articlename is not null");
            return (Criteria) this;
        }

        public Criteria andArticlenameEqualTo(String value) {
            addCriterion("articlename =", value, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameNotEqualTo(String value) {
            addCriterion("articlename <>", value, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameGreaterThan(String value) {
            addCriterion("articlename >", value, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameGreaterThanOrEqualTo(String value) {
            addCriterion("articlename >=", value, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameLessThan(String value) {
            addCriterion("articlename <", value, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameLessThanOrEqualTo(String value) {
            addCriterion("articlename <=", value, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameLike(String value) {
            addCriterion("articlename like", value, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameNotLike(String value) {
            addCriterion("articlename not like", value, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameIn(List<String> values) {
            addCriterion("articlename in", values, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameNotIn(List<String> values) {
            addCriterion("articlename not in", values, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameBetween(String value1, String value2) {
            addCriterion("articlename between", value1, value2, "articlename");
            return (Criteria) this;
        }

        public Criteria andArticlenameNotBetween(String value1, String value2) {
            addCriterion("articlename not between", value1, value2, "articlename");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(Integer value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(Integer value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(Integer value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(Integer value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(Integer value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<Integer> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<Integer> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(Integer value1, Integer value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(Integer value1, Integer value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andUsernoIsNull() {
            addCriterion("userno is null");
            return (Criteria) this;
        }

        public Criteria andUsernoIsNotNull() {
            addCriterion("userno is not null");
            return (Criteria) this;
        }

        public Criteria andUsernoEqualTo(Integer value) {
            addCriterion("userno =", value, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernoNotEqualTo(Integer value) {
            addCriterion("userno <>", value, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernoGreaterThan(Integer value) {
            addCriterion("userno >", value, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernoGreaterThanOrEqualTo(Integer value) {
            addCriterion("userno >=", value, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernoLessThan(Integer value) {
            addCriterion("userno <", value, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernoLessThanOrEqualTo(Integer value) {
            addCriterion("userno <=", value, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernoIn(List<Integer> values) {
            addCriterion("userno in", values, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernoNotIn(List<Integer> values) {
            addCriterion("userno not in", values, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernoBetween(Integer value1, Integer value2) {
            addCriterion("userno between", value1, value2, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernoNotBetween(Integer value1, Integer value2) {
            addCriterion("userno not between", value1, value2, "userno");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andChapternoIsNull() {
            addCriterion("chapterno is null");
            return (Criteria) this;
        }

        public Criteria andChapternoIsNotNull() {
            addCriterion("chapterno is not null");
            return (Criteria) this;
        }

        public Criteria andChapternoEqualTo(Integer value) {
            addCriterion("chapterno =", value, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternoNotEqualTo(Integer value) {
            addCriterion("chapterno <>", value, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternoGreaterThan(Integer value) {
            addCriterion("chapterno >", value, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternoGreaterThanOrEqualTo(Integer value) {
            addCriterion("chapterno >=", value, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternoLessThan(Integer value) {
            addCriterion("chapterno <", value, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternoLessThanOrEqualTo(Integer value) {
            addCriterion("chapterno <=", value, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternoIn(List<Integer> values) {
            addCriterion("chapterno in", values, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternoNotIn(List<Integer> values) {
            addCriterion("chapterno not in", values, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternoBetween(Integer value1, Integer value2) {
            addCriterion("chapterno between", value1, value2, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternoNotBetween(Integer value1, Integer value2) {
            addCriterion("chapterno not between", value1, value2, "chapterno");
            return (Criteria) this;
        }

        public Criteria andChapternameIsNull() {
            addCriterion("chaptername is null");
            return (Criteria) this;
        }

        public Criteria andChapternameIsNotNull() {
            addCriterion("chaptername is not null");
            return (Criteria) this;
        }

        public Criteria andChapternameEqualTo(String value) {
            addCriterion("chaptername =", value, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameNotEqualTo(String value) {
            addCriterion("chaptername <>", value, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameGreaterThan(String value) {
            addCriterion("chaptername >", value, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameGreaterThanOrEqualTo(String value) {
            addCriterion("chaptername >=", value, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameLessThan(String value) {
            addCriterion("chaptername <", value, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameLessThanOrEqualTo(String value) {
            addCriterion("chaptername <=", value, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameLike(String value) {
            addCriterion("chaptername like", value, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameNotLike(String value) {
            addCriterion("chaptername not like", value, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameIn(List<String> values) {
            addCriterion("chaptername in", values, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameNotIn(List<String> values) {
            addCriterion("chaptername not in", values, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameBetween(String value1, String value2) {
            addCriterion("chaptername between", value1, value2, "chaptername");
            return (Criteria) this;
        }

        public Criteria andChapternameNotBetween(String value1, String value2) {
            addCriterion("chaptername not between", value1, value2, "chaptername");
            return (Criteria) this;
        }

        public Criteria andLastvisitIsNull() {
            addCriterion("lastvisit is null");
            return (Criteria) this;
        }

        public Criteria andLastvisitIsNotNull() {
            addCriterion("lastvisit is not null");
            return (Criteria) this;
        }

        public Criteria andLastvisitEqualTo(Date value) {
            addCriterion("lastvisit =", value, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andLastvisitNotEqualTo(Date value) {
            addCriterion("lastvisit <>", value, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andLastvisitGreaterThan(Date value) {
            addCriterion("lastvisit >", value, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andLastvisitGreaterThanOrEqualTo(Date value) {
            addCriterion("lastvisit >=", value, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andLastvisitLessThan(Date value) {
            addCriterion("lastvisit <", value, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andLastvisitLessThanOrEqualTo(Date value) {
            addCriterion("lastvisit <=", value, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andLastvisitIn(List<Date> values) {
            addCriterion("lastvisit in", values, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andLastvisitNotIn(List<Date> values) {
            addCriterion("lastvisit not in", values, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andLastvisitBetween(Date value1, Date value2) {
            addCriterion("lastvisit between", value1, value2, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andLastvisitNotBetween(Date value1, Date value2) {
            addCriterion("lastvisit not between", value1, value2, "lastvisit");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNull() {
            addCriterion("deleteflag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIsNotNull() {
            addCriterion("deleteflag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteflagEqualTo(Boolean value) {
            addCriterion("deleteflag =", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotEqualTo(Boolean value) {
            addCriterion("deleteflag <>", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThan(Boolean value) {
            addCriterion("deleteflag >", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleteflag >=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThan(Boolean value) {
            addCriterion("deleteflag <", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagLessThanOrEqualTo(Boolean value) {
            addCriterion("deleteflag <=", value, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagIn(List<Boolean> values) {
            addCriterion("deleteflag in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotIn(List<Boolean> values) {
            addCriterion("deleteflag not in", values, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagBetween(Boolean value1, Boolean value2) {
            addCriterion("deleteflag between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andDeleteflagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleteflag not between", value1, value2, "deleteflag");
            return (Criteria) this;
        }

        public Criteria andModifyusernoIsNull() {
            addCriterion("modifyuserno is null");
            return (Criteria) this;
        }

        public Criteria andModifyusernoIsNotNull() {
            addCriterion("modifyuserno is not null");
            return (Criteria) this;
        }

        public Criteria andModifyusernoEqualTo(Integer value) {
            addCriterion("modifyuserno =", value, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifyusernoNotEqualTo(Integer value) {
            addCriterion("modifyuserno <>", value, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifyusernoGreaterThan(Integer value) {
            addCriterion("modifyuserno >", value, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifyusernoGreaterThanOrEqualTo(Integer value) {
            addCriterion("modifyuserno >=", value, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifyusernoLessThan(Integer value) {
            addCriterion("modifyuserno <", value, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifyusernoLessThanOrEqualTo(Integer value) {
            addCriterion("modifyuserno <=", value, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifyusernoIn(List<Integer> values) {
            addCriterion("modifyuserno in", values, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifyusernoNotIn(List<Integer> values) {
            addCriterion("modifyuserno not in", values, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifyusernoBetween(Integer value1, Integer value2) {
            addCriterion("modifyuserno between", value1, value2, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifyusernoNotBetween(Integer value1, Integer value2) {
            addCriterion("modifyuserno not between", value1, value2, "modifyuserno");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNull() {
            addCriterion("modifytime is null");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNotNull() {
            addCriterion("modifytime is not null");
            return (Criteria) this;
        }

        public Criteria andModifytimeEqualTo(Date value) {
            addCriterion("modifytime =", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotEqualTo(Date value) {
            addCriterion("modifytime <>", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThan(Date value) {
            addCriterion("modifytime >", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modifytime >=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThan(Date value) {
            addCriterion("modifytime <", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThanOrEqualTo(Date value) {
            addCriterion("modifytime <=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeIn(List<Date> values) {
            addCriterion("modifytime in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotIn(List<Date> values) {
            addCriterion("modifytime not in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeBetween(Date value1, Date value2) {
            addCriterion("modifytime between", value1, value2, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotBetween(Date value1, Date value2) {
            addCriterion("modifytime not between", value1, value2, "modifytime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bookcase
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bookcase
     *
     * @mbggenerated Mon Oct 16 17:33:47 GMT+08:00 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}