package com.chawuzhi.novel.mapper;

import com.chawuzhi.novel.domain.HistoryStore;
import com.chawuzhi.novel.domain.HistoryStoreExample;
import com.chawuzhi.novel.domain.HistoryStoreKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoryStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int countByExample(HistoryStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int deleteByExample(HistoryStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int deleteByPrimaryKey(HistoryStoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int insert(HistoryStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int insertSelective(HistoryStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    List<HistoryStore> selectByExampleWithBLOBs(HistoryStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    List<HistoryStore> selectByExample(HistoryStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    HistoryStore selectByPrimaryKey(HistoryStoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") HistoryStore record, @Param("example") HistoryStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExampleWithBLOBs(@Param("record") HistoryStore record, @Param("example") HistoryStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExample(@Param("record") HistoryStore record, @Param("example") HistoryStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(HistoryStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKeyWithBLOBs(HistoryStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_store
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKey(HistoryStore record);
}