package com.chawuzhi.novel.mapper;

import com.chawuzhi.novel.domain.TArticle;
import com.chawuzhi.novel.domain.TArticleExample;
import com.chawuzhi.novel.domain.TArticleWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int countByExample(TArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int deleteByExample(TArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer articleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int insert(TArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int insertSelective(TArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    List<TArticleWithBLOBs> selectByExampleWithBLOBs(TArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    List<TArticle> selectByExample(TArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    TArticleWithBLOBs selectByPrimaryKey(Integer articleno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TArticleWithBLOBs record, @Param("example") TArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TArticleWithBLOBs record, @Param("example") TArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TArticle record, @Param("example") TArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKeyWithBLOBs(TArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKey(TArticle record);
}