package com.chawuzhi.novel.mapper;

import com.chawuzhi.novel.domain.TCredit_history;
import com.chawuzhi.novel.domain.TCredit_historyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCredit_historyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int countByExample(TCredit_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int deleteByExample(TCredit_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer credithistoryno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int insert(TCredit_history record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int insertSelective(TCredit_history record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    List<TCredit_history> selectByExample(TCredit_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    TCredit_history selectByPrimaryKey(Integer credithistoryno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TCredit_history record, @Param("example") TCredit_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TCredit_history record, @Param("example") TCredit_historyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TCredit_history record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_history
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKey(TCredit_history record);
}