package com.chawuzhi.novel.mapper;

import com.chawuzhi.novel.domain.TSubscribe;
import com.chawuzhi.novel.domain.TSubscribeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int countByExample(TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int deleteByExample(TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer subscribeno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int insert(TSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int insertSelective(TSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    List<TSubscribe> selectByExample(TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    TSubscribe selectByPrimaryKey(Integer subscribeno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TSubscribe record, @Param("example") TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TSubscribe record, @Param("example") TSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subscribe
     *
     * @mbggenerated Mon Oct 16 17:40:37 GMT+08:00 2017
     */
    int updateByPrimaryKey(TSubscribe record);
}