package com.chawuzhi.novel.mapper;

import com.chawuzhi.novel.domain.TSystem_block;
import com.chawuzhi.novel.domain.TSystem_blockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSystem_blockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int countByExample(TSystem_blockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int deleteByExample(TSystem_blockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer blockNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int insert(TSystem_block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int insertSelective(TSystem_block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    List<TSystem_block> selectByExampleWithBLOBs(TSystem_blockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    List<TSystem_block> selectByExample(TSystem_blockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    TSystem_block selectByPrimaryKey(Integer blockNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TSystem_block record, @Param("example") TSystem_blockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TSystem_block record, @Param("example") TSystem_blockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TSystem_block record, @Param("example") TSystem_blockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TSystem_block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int updateByPrimaryKeyWithBLOBs(TSystem_block record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 15:59:23 GMT+08:00 2017
     */
    int updateByPrimaryKey(TSystem_block record);
}