package com.chawuzhi.novel.common.mapper;

import com.chawuzhi.novel.common.domain.TBook;
import com.chawuzhi.novel.common.domain.TBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int countByExample(TBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int deleteByExample(TBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int insert(TBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int insertSelective(TBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    List<TBook> selectByExampleWithBLOBs(TBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    List<TBook> selectByExample(TBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    TBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TBook record, @Param("example") TBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TBook record, @Param("example") TBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TBook record, @Param("example") TBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByPrimaryKeyWithBLOBs(TBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_book
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByPrimaryKey(TBook record);
}