package com.chawuzhi.novel.common.mapper;

import com.chawuzhi.novel.common.domain.TSystemBlock;
import com.chawuzhi.novel.common.domain.TSystemBlockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSystemBlockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int countByExample(TSystemBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int deleteByExample(TSystemBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer blockNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int insert(TSystemBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int insertSelective(TSystemBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    List<TSystemBlock> selectByExampleWithBLOBs(TSystemBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    List<TSystemBlock> selectByExample(TSystemBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    TSystemBlock selectByPrimaryKey(Integer blockNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TSystemBlock record, @Param("example") TSystemBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int updateByExampleWithBLOBs(@Param("record") TSystemBlock record, @Param("example") TSystemBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TSystemBlock record, @Param("example") TSystemBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TSystemBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int updateByPrimaryKeyWithBLOBs(TSystemBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_block
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    int updateByPrimaryKey(TSystemBlock record);
}