package com.chawuzhi.novel.common.mapper;

import com.chawuzhi.novel.common.domain.TUser_detail;
import com.chawuzhi.novel.common.domain.TUser_detailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUser_detailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int countByExample(TUser_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int deleteByExample(TUser_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int insert(TUser_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int insertSelective(TUser_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    List<TUser_detail> selectByExample(TUser_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    TUser_detail selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") TUser_detail record, @Param("example") TUser_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByExample(@Param("record") TUser_detail record, @Param("example") TUser_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TUser_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_detail
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    int updateByPrimaryKey(TUser_detail record);
}