package com.chawuzhi.novel.common.domain;

import com.chawuzhi.novel.common.base.BaseDomain;
import java.util.Date;

public class TBookcase extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.bookcase_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private Integer bookcaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.user_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.book_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.last_category_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private Integer lastCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.chapter_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private Integer chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.chapter_name
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.last_visit
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private Date lastVisit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.delete_flag
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.creater_no
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private String createrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.create_time
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.modifier
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookcase.moidfiy_time
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    private Date moidfiyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.bookcase_id
     *
     * @return the value of t_bookcase.bookcase_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public Integer getBookcaseId() {
        return bookcaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.bookcase_id
     *
     * @param bookcaseId the value for t_bookcase.bookcase_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setBookcaseId(Integer bookcaseId) {
        this.bookcaseId = bookcaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.user_id
     *
     * @return the value of t_bookcase.user_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.user_id
     *
     * @param userId the value for t_bookcase.user_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.book_id
     *
     * @return the value of t_bookcase.book_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.book_id
     *
     * @param bookId the value for t_bookcase.book_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.last_category_id
     *
     * @return the value of t_bookcase.last_category_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public Integer getLastCategoryId() {
        return lastCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.last_category_id
     *
     * @param lastCategoryId the value for t_bookcase.last_category_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setLastCategoryId(Integer lastCategoryId) {
        this.lastCategoryId = lastCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.chapter_id
     *
     * @return the value of t_bookcase.chapter_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.chapter_id
     *
     * @param chapterId the value for t_bookcase.chapter_id
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.chapter_name
     *
     * @return the value of t_bookcase.chapter_name
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.chapter_name
     *
     * @param chapterName the value for t_bookcase.chapter_name
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.last_visit
     *
     * @return the value of t_bookcase.last_visit
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public Date getLastVisit() {
        return lastVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.last_visit
     *
     * @param lastVisit the value for t_bookcase.last_visit
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setLastVisit(Date lastVisit) {
        this.lastVisit = lastVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.delete_flag
     *
     * @return the value of t_bookcase.delete_flag
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.delete_flag
     *
     * @param deleteFlag the value for t_bookcase.delete_flag
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.creater_no
     *
     * @return the value of t_bookcase.creater_no
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public String getCreaterNo() {
        return createrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.creater_no
     *
     * @param createrNo the value for t_bookcase.creater_no
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setCreaterNo(String createrNo) {
        this.createrNo = createrNo == null ? null : createrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.create_time
     *
     * @return the value of t_bookcase.create_time
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.create_time
     *
     * @param createTime the value for t_bookcase.create_time
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.modifier
     *
     * @return the value of t_bookcase.modifier
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.modifier
     *
     * @param modifier the value for t_bookcase.modifier
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookcase.moidfiy_time
     *
     * @return the value of t_bookcase.moidfiy_time
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public Date getMoidfiyTime() {
        return moidfiyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookcase.moidfiy_time
     *
     * @param moidfiyTime the value for t_bookcase.moidfiy_time
     *
     * @mbggenerated Thu Oct 26 18:02:09 GMT+08:00 2017
     */
    public void setMoidfiyTime(Date moidfiyTime) {
        this.moidfiyTime = moidfiyTime;
    }
}