package com.chawuzhi.novel.common.domain;

import com.chawuzhi.novel.common.base.BaseDomain;
import java.util.Date;

public class TSystemBlock extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.block_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Integer blockNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.block_id
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String blockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.block_name
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String blockName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.type
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.category
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.sortcol
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String sortcol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.isasc
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Byte isasc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.ifinish
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Byte ifinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.limitnum
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Integer limitnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.deleteflag
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Boolean deleteflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.target
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Short target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.creater_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String createrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.create_time
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.modifier
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.modify_time
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system_block.content
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.block_no
     *
     * @return the value of t_system_block.block_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Integer getBlockNo() {
        return blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.block_no
     *
     * @param blockNo the value for t_system_block.block_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setBlockNo(Integer blockNo) {
        this.blockNo = blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.block_id
     *
     * @return the value of t_system_block.block_id
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getBlockId() {
        return blockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.block_id
     *
     * @param blockId the value for t_system_block.block_id
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setBlockId(String blockId) {
        this.blockId = blockId == null ? null : blockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.block_name
     *
     * @return the value of t_system_block.block_name
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getBlockName() {
        return blockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.block_name
     *
     * @param blockName the value for t_system_block.block_name
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setBlockName(String blockName) {
        this.blockName = blockName == null ? null : blockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.type
     *
     * @return the value of t_system_block.type
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.type
     *
     * @param type the value for t_system_block.type
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.category
     *
     * @return the value of t_system_block.category
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.category
     *
     * @param category the value for t_system_block.category
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.sortcol
     *
     * @return the value of t_system_block.sortcol
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getSortcol() {
        return sortcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.sortcol
     *
     * @param sortcol the value for t_system_block.sortcol
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setSortcol(String sortcol) {
        this.sortcol = sortcol == null ? null : sortcol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.isasc
     *
     * @return the value of t_system_block.isasc
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Byte getIsasc() {
        return isasc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.isasc
     *
     * @param isasc the value for t_system_block.isasc
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setIsasc(Byte isasc) {
        this.isasc = isasc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.ifinish
     *
     * @return the value of t_system_block.ifinish
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Byte getIfinish() {
        return ifinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.ifinish
     *
     * @param ifinish the value for t_system_block.ifinish
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setIfinish(Byte ifinish) {
        this.ifinish = ifinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.limitnum
     *
     * @return the value of t_system_block.limitnum
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Integer getLimitnum() {
        return limitnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.limitnum
     *
     * @param limitnum the value for t_system_block.limitnum
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setLimitnum(Integer limitnum) {
        this.limitnum = limitnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.deleteflag
     *
     * @return the value of t_system_block.deleteflag
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Boolean getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.deleteflag
     *
     * @param deleteflag the value for t_system_block.deleteflag
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setDeleteflag(Boolean deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.target
     *
     * @return the value of t_system_block.target
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Short getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.target
     *
     * @param target the value for t_system_block.target
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setTarget(Short target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.creater_no
     *
     * @return the value of t_system_block.creater_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getCreaterNo() {
        return createrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.creater_no
     *
     * @param createrNo the value for t_system_block.creater_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setCreaterNo(String createrNo) {
        this.createrNo = createrNo == null ? null : createrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.create_time
     *
     * @return the value of t_system_block.create_time
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.create_time
     *
     * @param createTime the value for t_system_block.create_time
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.modifier
     *
     * @return the value of t_system_block.modifier
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.modifier
     *
     * @param modifier the value for t_system_block.modifier
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.modify_time
     *
     * @return the value of t_system_block.modify_time
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.modify_time
     *
     * @param modifyTime the value for t_system_block.modify_time
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system_block.content
     *
     * @return the value of t_system_block.content
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system_block.content
     *
     * @param content the value for t_system_block.content
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}