package com.chawuzhi.novel.common.domain;

import com.chawuzhi.novel.common.base.BaseDomain;
import java.util.Date;

public class TUser extends BaseDomain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Integer userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.account
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.reg_date
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Date regDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.sex
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Short sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.qq
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_logintime
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Date lastLogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.lineno
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String lineno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.type
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.vote_count
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Integer voteCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.delete_flag
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Byte deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.real_name
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.branch
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String branch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.bankno
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String bankno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.alipay_account
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String alipayAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.category
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.subcategory
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Integer subcategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modify_user_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Integer modifyUserNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modify_name
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String modifyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.openid
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.activeflag
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private Byte activeflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mail_token
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    private String mailToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_no
     *
     * @return the value of t_user.user_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Integer getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_no
     *
     * @param userNo the value for t_user.user_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setUserNo(Integer userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.account
     *
     * @return the value of t_user.account
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.account
     *
     * @param account the value for t_user.account
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.reg_date
     *
     * @return the value of t_user.reg_date
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.reg_date
     *
     * @param regDate the value for t_user.reg_date
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.sex
     *
     * @return the value of t_user.sex
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.sex
     *
     * @param sex the value for t_user.sex
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.qq
     *
     * @return the value of t_user.qq
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.qq
     *
     * @param qq the value for t_user.qq
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_logintime
     *
     * @return the value of t_user.last_logintime
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Date getLastLogintime() {
        return lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_logintime
     *
     * @param lastLogintime the value for t_user.last_logintime
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setLastLogintime(Date lastLogintime) {
        this.lastLogintime = lastLogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.lineno
     *
     * @return the value of t_user.lineno
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getLineno() {
        return lineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.lineno
     *
     * @param lineno the value for t_user.lineno
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setLineno(String lineno) {
        this.lineno = lineno == null ? null : lineno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.type
     *
     * @return the value of t_user.type
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.type
     *
     * @param type the value for t_user.type
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.vote_count
     *
     * @return the value of t_user.vote_count
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Integer getVoteCount() {
        return voteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.vote_count
     *
     * @param voteCount the value for t_user.vote_count
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setVoteCount(Integer voteCount) {
        this.voteCount = voteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.delete_flag
     *
     * @return the value of t_user.delete_flag
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Byte getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.delete_flag
     *
     * @param deleteFlag the value for t_user.delete_flag
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setDeleteFlag(Byte deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.real_name
     *
     * @return the value of t_user.real_name
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.real_name
     *
     * @param realName the value for t_user.real_name
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.branch
     *
     * @return the value of t_user.branch
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.branch
     *
     * @param branch the value for t_user.branch
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.bankno
     *
     * @return the value of t_user.bankno
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.bankno
     *
     * @param bankno the value for t_user.bankno
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setBankno(String bankno) {
        this.bankno = bankno == null ? null : bankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.alipay_account
     *
     * @return the value of t_user.alipay_account
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getAlipayAccount() {
        return alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.alipay_account
     *
     * @param alipayAccount the value for t_user.alipay_account
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setAlipayAccount(String alipayAccount) {
        this.alipayAccount = alipayAccount == null ? null : alipayAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.category
     *
     * @return the value of t_user.category
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.category
     *
     * @param category the value for t_user.category
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.subcategory
     *
     * @return the value of t_user.subcategory
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Integer getSubcategory() {
        return subcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.subcategory
     *
     * @param subcategory the value for t_user.subcategory
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setSubcategory(Integer subcategory) {
        this.subcategory = subcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modify_user_no
     *
     * @return the value of t_user.modify_user_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Integer getModifyUserNo() {
        return modifyUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modify_user_no
     *
     * @param modifyUserNo the value for t_user.modify_user_no
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setModifyUserNo(Integer modifyUserNo) {
        this.modifyUserNo = modifyUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modify_name
     *
     * @return the value of t_user.modify_name
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getModifyName() {
        return modifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modify_name
     *
     * @param modifyName the value for t_user.modify_name
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setModifyName(String modifyName) {
        this.modifyName = modifyName == null ? null : modifyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.openid
     *
     * @return the value of t_user.openid
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.openid
     *
     * @param openid the value for t_user.openid
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.activeflag
     *
     * @return the value of t_user.activeflag
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public Byte getActiveflag() {
        return activeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.activeflag
     *
     * @param activeflag the value for t_user.activeflag
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setActiveflag(Byte activeflag) {
        this.activeflag = activeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mail_token
     *
     * @return the value of t_user.mail_token
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public String getMailToken() {
        return mailToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mail_token
     *
     * @param mailToken the value for t_user.mail_token
     *
     * @mbggenerated Thu Oct 26 19:04:52 GMT+08:00 2017
     */
    public void setMailToken(String mailToken) {
        this.mailToken = mailToken == null ? null : mailToken.trim();
    }
}